# Generated by Django 5.1.6 on 2025-06-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_alter_blogs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('public', 'Published')], default='draft', max_length=10),
        ),
    ]
