# Generated by Django 5.2 on 2025-06-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0004_alter_blogs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
