# Generated by Django 5.2 on 2025-06-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0005_alter_blogs_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='categroy',
            new_name='category',
        ),
    ]
